### ISSUE TITLE
`ymdk/id75:vial` is broken in usevia.app due to `Fetching v2 definition failed`

### ISSUE THREAD

**Issue by C0rn3j** [vial-kb/vial-gui#239]
I have compiled the FW as is(`VIA_ENABLE = yes` is present) and flashed it - all good.

vial.rocks and the native app work fine.

usevia.app and native via app however both fail to connect to the keyboard with:

```yaml
Fetching v2 definition failed
Device: YMDK Idobao x YMDK ID75
Vid: 0x594D
Pid: 0x0075
```

This is on Arch Linux and Chromium 124.
